FROM  my-image

RUN  apk update
RUN  apk add nginx

RUN mkdir -p /usr/share/nginx/html
COPY index.html /usr/share/nginx/html/index.html
RUN mkdir -p /etc/nginx/conf.d
COPY myapp.conf /etc/nginx/conf.d/myapp.conf
RUN echo 'events {} http { include /etc/nginx/conf.d/*.conf; }' > /etc/nginx/nginx.conf

EXPOSE 8081

CMD ["nginx", "-g", "daemon off;"]



