print("hello world")
print("This is a simple Python script.")
print("It prints a greeting message to the console.")
print("You can run this script using Python interpreter.")
print("Make sure you have Python installed on your system.")